name: CI-CD

on:
  push:
    branches: ["main"]
  
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Contução da imagem docker
      uses: docker/build-push-action@v3.2.0
    with:
      context: ./src
      file: ./src/Dockerfile
      push: true
      tags:
        luanbruno/posticket-new:v1
        luanbruno/posticket-new:latest
        
